### ISSUE TITLE
annotateText  does not work properly

### ISSUE THREAD

**Issue by d48u** [JoggApp/laravel-natural-language#4] opened 2020-04-16 00:28 UTC
in NaturalLanguage.php method_exists returns false

e.g.
method_exists($annotation, 'entities') is false but entities occurs with dump ($annotation)

method_exists($annotation, 'sentiment') is true and work properly

**Comment by introwit** [comment] 2020-04-16 15:01
what is the key of entities array then when it's dumped? Can you PR a failing test and the fix, since the complete issue is a bit unclear from your comment so I am unable to reproduce it.

**Comment by introwit** [comment] 2020-09-10 18:12
closing since no reply.

**Closed as completed by introwit** 2020-09-10 18:12 UTC
