### ISSUE TITLE
method_exists don't work with php 7.4

### ISSUE THREAD

**Issue by bfontanet** [JoggApp/laravel-natural-language#6] opened 2021-06-11 06:38 UTC
For example, to get syntax(string) always return "null" (attach screenshots)

                        'sentences' => method_exists($syntax, 'sentences') ? $syntax->sentences() : null,
			'tokens' => method_exists($syntax, 'tokens') ? $syntax->tokens() : null,
			'language' => method_exists($syntax, 'language') ? $syntax->language() : null,

![2021-06-11_8-35-17](https://user-images.githubusercontent.com/10600143/121641863-0604a080-ca90-11eb-8991-6b68355f6246.jpg)
![2021-06-11_7-40-21](https://user-images.githubusercontent.com/10600143/121641866-069d3700-ca90-11eb-87b2-74d618edcc7b.jpg)

**Comment by introwit** [comment] 2021-06-11 13:36
Hi, can you PR a failing test or steps to reproduce? It does work for us and everyone else.

**Comment by introwit** [comment] 2021-08-05 21:08
closing since no reply.

**Closed as completed by introwit** 2021-08-05 21:08 UTC
