### ISSUE TITLE
Not installing in laravel V9

### ISSUE THREAD

**Issue by SilvaEngComp** [JoggApp/laravel-natural-language#10] opened 2022-04-11 19:30 UTC
Hi! When I try to install, I Got that problem:
  Problem 1
    - Root composer.json requires joggapp/laravel-natural-language ^7.0 -> satisfiable by joggapp/laravel-natural-language[v7.0.0, v7.0.1].   
    - joggapp/laravel-natural-language[v7.0.0, ..., v7.0.1] require illuminate/support 9.* -> found illuminate/support[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require joggapp/laravel-natural-language:*" to figure out if any version is installable, or "composer require joggapp/laravel-natural-language:^2.1" if you know which you need.

I tried to install especific version like "composer require joggapp/laravel-natural-language:^7.0.1", but generated that problem too:

 Problem 1
    - Root composer.json requires joggapp/laravel-natural-language 7.0.1 -> satisfiable by joggapp/laravel-natural-language[v7.0.1].
    - joggapp/laravel-natural-language v7.0.1 requires illuminate/support 9.* -> found illuminate/support[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by introwit** [comment] 2022-04-11 19:33
@SilvaEngComp some other requirements are conflicting within your app. We have it working well with our Laravel v9 app and also the tests assert that. Closing since the issue isn't related to this package.

**Closed as completed by introwit** 2022-04-11 19:33 UTC

**Comment by SilvaEngComp** [comment] 2022-04-11 19:50
Thank you! You right! I created a new project and the installation runned well. There were some packages not updated. I made the modifications, remove vendor package and run composer install. Now it's running well.

**Comment by SilvaEngComp** [comment] 2022-04-11 20:16
Thank you! You right! I was musted to update my packages!
